export enum InAppTaskCycle {
    bagging     = 'balut',
    posponedbagging = 'balutposponed',
    cp          = 'debung',
    posponedCp  = 'debungposponed',
    rejectedCp  = 'debungrejected',
    qc          = 'qc',
    qcSv        = 'qcsv',
    harvest     = 'tuai',
    harvestSv   = 'harvestsv',
    pp          = 'pollenprep',
    ppSv        = 'pollenprepsv',
    posponedpp  = 'posponedpollenprep',
    pollenPrepForm  = 'pollen-prep-form',
}